---
title: "Andrew G. Argeros's CV"
author: Andrew G. Argeros
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['C:/Users/aargeros/Documents/GitHub/andrewargeros.github.io/Back End Code/dd_cv.css', 'resume']
    self_contained: true
---

```{css, echo=FALSE}
.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0.2rem;
  --sidebar-background-color: #f7fbff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("C:/Users/aargeros/Documents/GitHub/andrewargeros.github.io/Back End Code/cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1IKH1V00AzJuF0vuKcjdQx_4N7e7apqaQv9jBzubm2vA/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
#datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("View this CV online with links at andrewargeros.com/cv")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/andrewargeros/andrewargeros.github.io/raw/master/argeros_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Programming {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```


Languages {#lskills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_spoken_bars()
```

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

References are available upon request.

Last updated on `r Sys.Date()`.



Main
================================================================================

Andrew G. Argeros {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('research_positions')
```



Industry Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('industry_positions')
```

<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>
<br>
<br>

Data Science Projects {data-icon=chart-line}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('data_science_competitions')
```



Publications {data-icon=newspaper}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('about_me_press')
```

<br>
<br>
<br>

```{r}
CV %<>% print_links()
```

